source-file ~/.config/tmux/tmux.reset.conf
set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

set -g prefix ^A
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 10            # small delay for vi mode (10ms)
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g mouse on                  # enable mouse support
set -g status-position top       # macOS / darwin style
set -g default-terminal "${TERM}"
setw -g mode-keys vi
set -g status-style bg=#0f0f0f
set -g window-style bg=#131418
set -g window-active-style bg=#0f0f0f
setw -g window-status-current-style bg=#4276ff
# Set default shell to nushell with proper initialization
set-option -g default-shell /bin/bash
set-option -g default-command "/usr/local/bin/nu -l"

